language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: 7

before_install:
    - pip install codecov

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - codecov
