name:           c33s/construction-kit-bundle
type:           symfony-bundle
description:    Attach files to any (Propel) object using Symfony2

homepage:       "https://github.com/vworldat/ConstructionKitBundle"
license:        ["MIT"]

authors:
  - name:       David
    email:      office@web-emerge.com
    homepage:   'http://web-emerge.com/'

autoload:
    psr-4:
        'C33s\ConstructionKitBundle\': ''

minimum-stability: stable

require:
    php:                                        '>=5.4.0'

    c33s/composer-construction-kit-installer:   '*'
    c33s/symfony-config-manipulator-bundle:     '*'

    symfony/monolog-bundle:                     '~2.4'
    symfony/symfony:                            '~2.3'
    sensio/generator-bundle:                    '~2.3'

require-dev:
    phpunit/phpunit:        '~4.8'
    fabpot/php-cs-fixer:    '~1.10'

extra:
    c33s-building-blocks:
        - C33s\ConstructionKitBundle\BuildingBlock\ConstructionKitBuildingBlock
